### ISSUE TITLE
Add support for system level cve allowlist

### ISSUE THREAD

**Issue by kristinnardal2** [goharbor/terraform-provider-harbor#223] opened 2022-06-03 09:36 UTC
**Is your feature request related to a problem? Please describe.**
There is currently some support for project level cve allowlist, although this is not documented.

Harbor also has support for a system level cve allowlists, there are GET and PUT requests in the Harbor REST api to get and update the cve allowlist.

**Describe the solution you'd like**
I would like to have a new resource called `harbor_system_cve_allowlist` where I can specify the system level cve allowlist.

**Describe alternatives you've considered**
We could also add a `cve_allowlist` argument to the `harbor_config_system` resource if that's easier to implement. I don't think it is however, since it can't be set with the same API call that `harbor_config_system` is using. The only reason to have it here is that in the Harbor GUI, these options are all in the same tab in the setting.

**Comment by lindhe** [comment] 2022-06-10 13:29
Duplicate of #206

**Comment by kristinnardal2** [comment] 2022-06-10 13:54
@lindhe actually no.
That issue is only concerning project level cve allowlists, for which there is some undocumented support for.
This issue asks for a system level cve allowlist, like you can define in the Harbor GUI.

**Comment by naitmare01** [comment] 2022-11-28 10:58
I have now written a PR that should address this issue. :)

**Closed** 2023-06-05 19:10 UTC
